### ISSUE TITLE
jCard PUT should return etag

### ISSUE THREAD

**Issue by Henni** [fruux/sabre-dav#732] opened 2015-10-29 13:45 UTC
A request like the following should return a new etag for the updated/created content, to allow further editing without having to GET the jcard in advance.
```
curl 'http://testuser:testpasswd@localhost:8080/remote.php/carddav/addressbooks/testuser/contacts/584f0060-0132-45a0-8b89-6ceb07bc5268.vcf' -X PUT -H 'Content-Type: application/vcard+json' --data-binary '["vcard",[["version",{},"text","4.0"],["prodid",{},"text","-//Sabre//Sabre VObject 3.4.7//EN"],["n",{},"text","Henni"],["uid",{},"text","584f0060-0132-45a0-8b89-6ceb07bc5268"],["rev",{},"timestamp","2015-10-27T16:52:39+00:00"],["fn",{},"text","Henni"]]]'
```

Therefore sabre has to return the newly generated etag, even though the jCard was converted to a vCard internally.

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment] 2015-10-29 15:06
basically because of this code path no etag is returned

https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Server.php#L1041-L1051

**Comment by evert** [comment] 2015-10-29 15:25
That is expected behavior, because we basically no longer guarantee binary equivalence. If we were to store the jCards then we could.

**Comment by DeepDiver1975** [comment] 2015-10-29 16:00
so the client has to propfind to get the etag - is that etag then valid?

**Comment by evert** [comment] 2015-10-29 16:44
Yes it is. Basically, the etag needs to change if the representation (response body in GET) changes.

Returning an ETag from a PUT basically says "I stored the resource, if call `GET` here you'll get the exact same thing back _unless_ the representation changes".

Since it's likely we send back a slightly different response than the user sent us, the etag in the initial PUT would be wrong, but immediately after that it's correct.

You could add a header `Prefer: return=representation` to get the new response back _and_ the new etag, but sabre/dav does not support that yet (although I'd really like to).

**Comment by evert** [comment] 2016-01-05 02:13
Closing due to no further feedback

**Closed by evert** 2016-01-05 02:13 UTC
Labels: invalid
