### ISSUE TITLE
404 Handle with no parstat

### ISSUE THREAD

**Issue by cedtaz** [fruux/sabre-dav#850] opened 2016-06-10 08:50 UTC
Hey, 

I have a problem with Thunderbird and plugin Sogo. When we delete a contact on addressbook server, the modification is not appear on the client.
I create [PR#849](https://github.com/fruux/sabre-dav/pull/849)

Thanks.

**Comment by evert** [comment] 2016-06-10 21:20
Did you try submitting this bug report at the Sogo bug tracker. 9 times out of 10 the problem is with Sogo.

**Comment by cedtaz** [comment] 2016-06-24 06:29
I submitted a bug report at the Sogo  bug tracker : https://sogo.nu/bugs/view.php?id=3732

**Comment by evert** [comment] 2016-06-27 22:51
Closing this as. Feel free to reopen if it turns out this is a sabredav-related bug.

**Closed by evert** 2016-06-27 22:51 UTC
