### ISSUE TITLE
Conflicts: Scheduling vs Synchronization

### ISSUE THREAD

**Issue by kriswebdev** [fruux/sabre-dav#827] opened 2016-05-01 18:31 UTC
Hi,

sabre/dav makes some changes on the server-side calendar objects when updating PARTSTAT of participants (iTip local delivery processing), that could conflict with local-side changes.

Scenario:

- Organizer creates a calender object and invites Bob and Alice, both local accounts.
- sabre/dav creates three calendar objects: one in Organizer calendar, one in Alice calendar, one in Bob calendar. Let's say for simplicity that all calendars have a sync token of `1` and all calendar objects an etag `E1` at this point.
- Now, Bob and Alice both synchronize their agendas and get the invite.
- Bob ACCEPT the invite and tries to synchronize its calendar.
- Bob synchronization works as expected. sabre/dav updates the calendar objects of Organizer, Bob and Alice with Bob PARTSTAT:ACCEPTED. When doing that, sabre/dav increments all agendas (Organizer, Bob and Alice) sync token to `2` and all calendar objects to etag `E2`.
- Alice has not synchronized yet. Locally, she's still at sync token `1`.
- Alice ACCEPT the invite and tries to synchronize its agenda.
- **CONFLICT.** Alice is using iOS or DAVDroid. Before doing the request, these CalDAV clients do a PROPFIND. Alice CalDAV client recognizes that the calendar object has changed on the server, due to sync token = `2` and etag `E2`. Her local change (Alice PARTSTAT:ACCEPTED) is never sent to the server. Instead, the CalDAV client overwrites Alice local calendar object with the server version (where Bob is PARTSTAT:ACCEPTED).

Nobody knows that Alice accepted the event. Poor Alice.

My purpose is to use CalDAV to manage events with numerous participants (members of the site), that could answer via Web or via phone. I can't expect everybody to always be in sync with the server when replying to the event.

I believe this is more a specification (RFC) problem than a bug, but I'd like to have your opinion and eventual workaround.

I don't see how sabre/dav could handle this: not updating the event during synchronization is a bad option, and there's no way for sabre to know if the synchronization will follow a PUT request or not. Maybe the client should better handle conflicts, but who's going to tell Apple to better manage conflicts if that's not specified in the RFC...

**Comment by evert** [comment] 2016-05-02 09:27
Hi @kriswebdev ,

There is something called a 'Schedule-Tag' which is something sabre/dav does not yet implement. It's a bit of a looser version of the ETag. I don't know 100% sure but if it's supported it _may_ solve your problem. I believe so at least =) What I don't know is if apple products implement it.

So for now the sanest thing seems to be to close this ticket as a duplicate of #501

**Closed by evert** 2016-05-02 09:27 UTC
